import { connectDB } from "../../db.js";

export async function handler(event, context) {
  try {
    const { prompt, creatorId } = JSON.parse(event.body);
    const db = await connectDB();

    // Example: simple HTML game generation
    const gameHtml = `
      <html>
      <head><title>Game: ${prompt}</title></head>
      <body>
        <h1>${prompt}</h1>
        <p>This is a generated game!</p>
      </body>
      </html>
    `;

    const result = await db.collection("games").insertOne({
      title: prompt,
      creatorId,
      gameUrl: `/games/${Date.now()}.html`,
      language: "HTML",
      description: "Generated by Nathen bot",
      code: gameHtml,
      votes: 0,
      createdAt: new Date().toISOString()
    });

    return {
      statusCode: 200,
      body: JSON.stringify({ gameId: result.insertedId, gameUrl: `/games/${Date.now()}.html` })
    };
  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ error: err.message }) };
  }
}
