import { connectDB } from "../../db.js";

export async function handler(event, context) {
  try {
    if (!event.body) {
      return { statusCode: 400, body: "Missing request body" };
    }

    const { prompt, creatorId } = JSON.parse(event.body);
    if (!prompt || !creatorId) {
      return { statusCode: 400, body: "Missing prompt or creatorId" };
    }

    const db = await connectDB();

    // Generate a unique file name for the game
    const fileId = Date.now();
    const gameUrl = `/games/${fileId}.html`;

    // Generate basic game HTML
    const gameHtml = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Game: ${prompt}</title>
      </head>
      <body>
        <h1>${prompt}</h1>
        <p>This is a generated game!</p>
      </body>
      </html>
    `;

    // Insert into database
    const result = await db.collection("games").insertOne({
      title: prompt,
      creatorId,
      gameUrl,
      language: "HTML",
      description: "Generated by Nathen bot",
      code: gameHtml,
      votes: 0,
      createdAt: new Date().toISOString()
    });

    return {
      statusCode: 200,
      body: JSON.stringify({
        gameId: result.insertedId,
        gameUrl
      })
    };

  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ error: err.message }) };
  }
}
